SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

export PYTHONPATH:=$(PWD)/Mac_verif:$(PYTHONPATH)

VERILOG_SOURCES=$(PWD)/verilog/mkMac.v

EXTRA_ARGS = --trace --trace-structs

TOPLEVEL = mkMac
MODULE   := test_Mac

include $(shell cocotb-config --makefiles)/Makefile.sim
