SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

export PYTHONPATH:=$(PWD)/Sam_verif:$(PYTHONPATH)

VERILOG_SOURCES=$(PWD)/verilog/mkSam.v

EXTRA_ARGS = --trace --trace-structs

TOPLEVEL = mkSam
MODULE   := test_Sam

include $(shell cocotb-config --makefiles)/Makefile.sim
